const icons={leave:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18m-13 5 3 3 5-5"/>',finger:'<path d="M8 20c2-3 2-6 2-9a2 2 0 0 1 4 0c0 5-1 8-2 10M5 17c1-2 1-4 1-6a6 6 0 0 1 12 0c0 4-.5 7-1 9M3 11a9 9 0 0 1 18 0"/>',room:'<path d="M4 21V3h12v18M2 21h20M16 8h4v13M11 12h1"/>',doc:'<path d="M14 2H5v20h14V7ZM14 2v6h5M8 12h8M8 16h6"/>',folder:'<path d="M3 7V4h6l3 3h9v14H3ZM3 11h18"/>',supplier:'<path d="M8 4H4v18h16V4h-4M8 2h8v5H8ZM8 12l2 2 5-5M8 18h8"/>',it:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4m0-14v4m0 2v1"/>',car:'<path d="m4 9 2-6h12l2 6M3 9h18v10H3ZM6 19v3m12-3v3M6 13h2m8 0h2"/>'};
const dcs='https://hrnano32-maker.github.io/Document-Control-System01/';
const forms=[['people','leave','ใบลาออนไลน์','ยื่นลาเต็มวันหรือครึ่งวัน แนบเอกสาร และดูสิทธิ์ลาคงเหลือ','https://onlineutility.app/leave-form-nano.html'],['people','finger','แจ้งสแกนนิ้วไม่ติดและอื่น ๆ','แจ้งปัญหาการสแกนเวลาเข้า–ออก และส่งรายการให้ตรวจสอบ','https://hrnano32-maker.github.io/Fingerprint-Exception-Form/'],['people','room','บันทึกการใช้ห้องประชุม','บันทึกการใช้ห้องประชุม ดูสถานะห้อง และรายการใช้งาน','https://onlineutility.app/booking-app.html'],['docs','doc','ใบ DAR ออนไลน์','ขอจัดทำ แก้ไข หรือยกเลิกเอกสาร ผ่านระบบควบคุมเอกสาร',dcs],['docs','folder','ระบบควบคุมเอกสาร','ทะเบียนเอกสาร Master List รับทราบ ดาวน์โหลด และแจกจ่ายเอกสาร',dcs],['docs','supplier','ประเมินผู้ขาย / Supplier','ประเมินผู้ขาย คำนวณคะแนนและเกรด พร้อมพิมพ์ใบประเมิน','https://onlineutility.app/supplier-evaluation.html'],['support','it','แจ้งปัญหา IT','แจ้งปัญหาอีเมลหรือคอมพิวเตอร์ พร้อมแนบภาพประกอบ','https://hrnano32-maker.github.io/IT-Problem-Report/'],['support','car','ข้อมูลการใช้รถแผนกจัดส่ง','บันทึกเลขไมล์ ค่าน้ำมัน และค่าแก๊สของรถแผนกจัดส่ง พร้อมดูรายงาน','https://hrnano32-maker.github.io/Vehicle-Mileage-Control/'],['support','car','ระบบจองรถส่วนกลาง','จองรถส่วนกลางสำหรับการใช้งานของบริษัท และตรวจสอบรายการจอง','https://onlineutility.app/online-car-booking.html'],['support','folder','แบบฟอร์มเบิกของ','บันทึกรายการขอเบิกวัสดุหรืออุปกรณ์ และติดตามรายการเบิก','https://onlineutility.app/supply-request-form.html']];
forms.forEach(([group,icon,title,description,url],i)=>{const el=document.createElement('article');el.className='card'+(icon==='room'?' meeting':'');el.innerHTML=`<div class="card-top"><span class="icon"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${icons[icon]}</svg></span><span class="card-number">${String(i+1).padStart(2,'0')}</span></div><h3>${title}</h3><p>${description}</p>${url?`<a class="action" href="${url}" target="_blank" rel="noopener noreferrer" aria-label="เปิด${title} ในหน้าต่างใหม่">${icon==='doc'?'เปิดระบบเพื่อยื่น DAR':'เปิดใช้งาน'}</a>`:'<span class="action pending">รอเชื่อมลิงก์</span>'}`;document.getElementById(group+'-cards').append(el);});
const dialog=document.getElementById('install-dialog');let deferred;
function showInstall(){document.getElementById('installed').hidden=!matchMedia('(display-mode: standalone)').matches;document.getElementById('instructions').hidden=matchMedia('(display-mode: standalone)').matches;dialog.showModal();}
document.getElementById('install').onclick=async()=>{if(deferred){await deferred.prompt();await deferred.userChoice;deferred=null;document.getElementById('native-install').hidden=true;}else{showInstall();}};document.getElementById('guide').onclick=showInstall;document.getElementById('close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('native-install').hidden=false;document.getElementById('install').textContent='ติดตั้งแอป';document.getElementById('instructions').hidden=true;document.getElementById('installed').hidden=true;if(!dialog.open)dialog.showModal();});
document.getElementById('native-install').onclick=async()=>{if(!deferred)return;try{await deferred.prompt();const choice=await deferred.userChoice;if(choice.outcome==='accepted'){dialog.close();}deferred=null;document.getElementById('native-install').hidden=true;}catch(err){document.getElementById('instructions').hidden=false;}};window.addEventListener('appinstalled',()=>{document.getElementById('native-install').hidden=true;document.getElementById('install').textContent='ติดตั้งแล้ว';dialog.close();});
function connectivity(){document.getElementById('offline').hidden=navigator.onLine;}window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);connectivity();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=20261007-9',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
